export const nav = [
  {
    id: 1,
    link: ".",
    name: "OPIEKA",
    sub: [
      {
        link: "",
        name: "PET SITTING",
      },
      {
        link: "",
        name: "SITTERZY",
      },
      {
        link: "",
        name: "ADOPCJE",
      },
      {
        link: "",
        name: "ORGANIZACJE",
      },
    ],
  },
  {
    id: 2,
    link: "/blog",
    name: "ARTYKUŁY",
    sub: [
      {
        link: "/blog/koty/1",
        name: "KOTY",
        cat: [
          {
            id: "sub",
            name: "WSZYSTKIE",
            query: "",
            desc: "Koty są jednymi z najbardziej enigmatycznych i niezależnych zwierząt na naszej planecie. Ich finezja, charyzma i niezwykła zdolność do nawiązywania silnych więzi z ludźmi sprawiają, że są nieodłącznym elementem naszych domów i serc. Na naszej stronie znajdziesz artykuły, które zabiorą Cię w podróż po różnorodnych aspektach życia kota - od ciekawostek o ich pochodzeniu i historii, przez porady dotyczące pielęgnacji, zdrowia i żywienia, po zgłębianie różnych zachowań i charakterystyk poszczególnych ras.",
            title: "Koty - artykuły",
          },
          {
            id: "sub1",
            name: "ADOPCJA",
            query: "adopcja_kota",
            desc: "Zastanawiasz się nad adopcją kota? Dowiedz się, jak znaleźć swojego nowego futrzanego przyjaciela i jak przygotować się na wspólne życie. Poznaj proces adopcji, korzyści płynące z przygarnięcia kota ze schroniska oraz porady na temat integracji nowego pupila z pozostałymi domownikami.",
            title: "Adopcja kota - jak znaleźć swojego przyjaciela",
          },
          {
            id: "sub2",
            name: "RASY",
            query: "rasy_kotow",
            desc: "Zwiedź fascynujący świat różnych ras kotów. Poznaj charakterystykę i osobowość poszczególnych ras, aby wybrać kota, który najlepiej pasuje do Twojego stylu życia. Odkryj różnice w wymaganiach pielęgnacyjnych i aktywności fizycznej między rasami oraz dowiedz się, jakie są najbardziej popularne rasy na świecie.",
            title: "Rasy kotów - różnorodność charakterów i uroków",
          },
          {
            id: "sub3",
            name: "GRY I ZABAWY",
            query: "gry_i_zabawy_kota",
            desc: "Zabawa jest ważna dla zdrowia i dobrej kondycji kota. Odkryj kreatywne gry i zabawy, które wzbogacą życie Twojego pupila. Dowiedz się, jak zaangażować kota w interaktywne zabawy, które będą stymulować jego zmysły i zachęcać do aktywności fizycznej. Poznaj również zabawki, które pomogą utrzymać kota w dobrej formie psychicznej i fizycznej.",
            title: "Gry i zabawy dla kota - radość i aktywność",
          },
          {
            id: "sub4",
            name: "TRANSPORT",
            query: "transport_kota",
            desc: "Czasem podróż z kotem może być wyzwaniem. Dowiedz się, jak zapewnić swojemu kotu komfort i bezpieczeństwo podczas podróży. Poznaj zasady podróżowania z kotem samochodem, pociągiem czy samolotem, oraz jak odpowiednio przygotować kota do podróży. Odkryj różne rodzaje transporterów i akcesoriów, które ułatwią przemieszczanie się z kotem.",
            title: "Transport kota - podróż z wygodą i bezpieczeństwem",
          },
          {
            id: "sub5",
            name: "WYCHOWANIE",
            query: "wychowanie_kota",
            desc: "Dobra edukacja to podstawa. Zyskaj cenne wskazówki dotyczące wychowywania kota i rozwiązywania typowych problemów behawioralnych. Dowiedz się, jak nauczyć kota korzystania z kuwety, wychowywać go w zgodzie z innymi zwierzętami i uczyć odpowiedniego zachowania w domu. Poznaj metody pozytywnego wzmocnienia i budowania zaufania z kotem.",
            title: "Wychowanie kota - jak zbudować harmonijną więź",
          },
          {
            id: "sub6",
            name: "ZDROWIE I PIELEGNACJA",
            query: "zdrowie_i_pielegnacja_kota",
            desc: "Zdrowy kot to szczęśliwy kot. Dowiedz się o podstawowych zasadach pielęgnacji i jak dbać o zdrowie swojego kota. Odkryj, jak regularnie monitorować stan zdrowia kota, jak radzić sobie z powszechnymi problemami zdrowotnymi oraz jak zapobiegać chorobom. Poznaj również najlepsze praktyki związane z pielęgnacją sierści, pazurów, zębów i uszu kota.",
            title: "Zdrowie i pielęgnacja kota - troska o dobre samopoczucie",
          },
          {
            id: "sub7",
            name: "ŻYWIENIE",
            query: "zywienie_kota",
            desc: "Dobra dieta to podstawa zdrowego życia. Odkryj, jak odpowiednio odżywiać swojego kota, aby zapewnić mu pełnowartościowe i smaczne posiłki. Poznaj zasady żywienia kota w różnych fazach życia, jakie są najlepsze składniki diety i jakie są wymagania żywieniowe kotów. Dowiedz się również, jakie pokarmy należy unikać, aby zapobiegać problemom zdrowotnym.",
            title: "Żywienie kota - smaczne i zdrowe posiłki",
          },
          {
            id: "sub8",
            name: "KOCIĘTA",
            query: "kocieta",
            desc: "Kocięta to urocze maleństwa pełne energii. Dowiedz się, jak zadbać o kocięta, by zdrowo rosły i prawidłowo się rozwijały. Poznaj odpowiednie metody karmienia i pielęgnacji małych kotków, aby zapewnić im najlepszy start w życie. Dowiedz się również, jak zachować bezpieczeństwo kociąt w domu i jakie szczepienia są niezbędne dla ich zdrowia.",
            title: "Kocięta - początki pięknej przygody",
          },
        ],
      },
      {
        link: "/blog/psy/1",
        name: "PSY",
        cat: [
          {
            id: "dog",
            name: "WSZYSTKIE",
            query: "",
            desc: "Psy są wyjątkowymi towarzyszami człowieka, znane ze swojej lojalności, oddania i inteligencji. Na naszej stronie znajdziesz pasjonujące artykuły, które zabiorą Cię w fascynującą podróż po różnych aspektach życia psa. Dowiesz się o aktywności sportowej i rozrywce dla pupila, ważnych kwestiach związanych z transportem, profesjonalnym wychowaniem i skuteczną pielęgnacją. Poznasz również tajniki zrozumienia potrzeb żywieniowych oraz wskazówki dotyczące opieki nad szczeniętami.",
            title: "Psy - artykuły",
          },
          {
            id: "dog7",
            name: "RASY",
            query: "rasy_psow",
            desc: "Rasy psów to fascynujący świat różnorodności. Poznaj charakterystykę i osobowość poszczególnych ras, aby wybrać psa, który najlepiej pasuje do Twojego stylu życia. Odkryj różnice w wymaganiach pielęgnacyjnych, aktywności fizycznej i temperamentu między rasami, oraz dowiedz się, jakie są najpopularniejsze rasy na świecie.",
            title: "Rasy psów - cechy charakterystyczne i osobowości",
          },
          {
            id: "dog1",
            name: "SPORT I ZABAWA",
            query: "sport_i_zabawa_psa",
            desc: `Aktywność fizyczna i umysłowa jest kluczowa dla zdrowia i szczęścia psa. Dowiedz się o różnych sportach i zabawach, które możesz uprawiać ze swoim psem, aby wzmocnić waszą więź, utrzymać kondycję oraz zapewnić rozrywkę i satysfakcję dla twojego pupila.`,
            title: "Sport i zabawa dla psa - klucz do szczęścia",
          },
          {
            id: "dog2",
            name: "TRANSPORT PSA",
            query: "transport_psa",
            desc: `Podróżowanie z psem może być wyzwaniem, ale także okazją do tworzenia niezapomnianych wspomnień. Poznaj zasady podróżowania z psem samochodem, pociągiem czy samolotem, oraz jak zapewnić mu komfort i bezpieczeństwo w trakcie podróży.`,
            title: "Transport psa - jak bezpiecznie podróżować",
          },
          {
            id: "dog3",
            name: "WYCHOWANIE PSA",
            query: "wychowanie_psa",
            desc: `Dobra edukacja i odpowiednie wychowanie są kluczowe dla zachowania psa jako zrównoważonego i posłusznego towarzysza. Dowiedz się, jak nauczyć psa podstawowych komend, jak radzić sobie z problemami behawioralnymi oraz jak budować zaufanie i pozytywną więź z twoim czworonogiem.`,
            title: "Wychowanie psa - budowanie więzi i zaufania",
          },
          {
            id: "dog4",
            name: "ZDROWIE I PIELĘGNACJA PSA",
            query: "zdrowie_i_pielegnacja_psa",
            desc: `Zdrowie to podstawa dobrej jakości życia psa. Dowiedz się o podstawowych zasadach pielęgnacji i jak dbać o zdrowie twojego pupila. Odkryj, jak regularnie monitorować stan zdrowia psa, jak radzić sobie z powszechnymi problemami zdrowotnymi oraz jak zapobiegać chorobom.`,
            title: "Zdrowie i pielęgnacja psa - troska o dobre samopoczucie",
          },
          {
            id: "dog5",
            name: "ŻYWIENIE PSA",
            query: "zywienie_psa",
            desc: `Dobra dieta to klucz do zdrowego i pełnego energii psa. Odkryj, jak odpowiednio odżywiać swojego pupila, aby zapewnić mu pełnowartościowe i smaczne posiłki. Poznaj zasady żywienia psa w różnych fazach życia, jakie są najlepsze składniki diety i jakie są wymagania żywieniowe.`,
            title: "Żywienie psa - zdrowe i smaczne posiłki",
          },
          {
            id: "dog6",
            name: "SZCZENIĘTA",
            query: "szczenieta",
            desc: `Szczenięta to urocze maleństwa, które potrzebują szczególnej opieki i uwagi. Dowiedz się, jak zadbać o szczenię w okresie wzrostu i jak odpowiednio je karmić, aby zapewnić mu zdrowy rozwój. Poznaj również ważne aspekty związane z wczesnym socjalizowaniem i szkoleniem szczeniąt.`,
            title: "Szczenięta - zdrowy rozwój i dobre nawyki",
          },
        ],
      },
      {
        link: "/blog/gryzonie/1",
        name: "GRYZONIE",
        cat: [
          {
            id: "rodents",
            name: "WSZYSTKIE",
            query: "",
            desc: "Znajdź tutaj artykuły dotyczące różnorodnych gatunków gryzoni oraz ich pielęgnacji, zdrowia, wychowania i zabawy. Dowiedz się więcej o tych uroczych stworzeniach i jak zapewnić im najlepszą opiekę.",
            title: "Gryzonie - artykuły",
          },
          {
            id: "rodents1",
            name: "ADOPCJA",
            query: "adopcja_gryzonia",
            desc: "Jeśli rozważasz adopcję gryzonia jako nowego pupila, przeczytaj nasze artykuły na ten temat. Dowiedz się, jak przygotować się do adopcji, jakie gatunki są odpowiednie dla Twojego stylu życia i jak zapewnić im kochający dom.",
            title: "Adopcja gryzoni - co warto wiedzieć",
          },
          {
            id: "rodents2",
            name: "GATUNKI",
            query: "gatunki_gryzoni",
            desc: "Odkryj różnorodność gatunków gryzoni - od małych i uroczych chomików po inteligentne myszy i chwytliwe wiewiórki. Poznaj ich charakterystyczne cechy i wymagania, aby zapewnić im zdrowe i szczęśliwe życie.",
            title: "Różnorodność gatunków gryzoni - poznaj je wszystkie",
          },
          {
            id: "rodents3",
            name: "WYCHOWANIE I ZABAWA",
            query: "wychowanie_i_zabawa_gryzoni",
            desc: "Dowiedz się, jak prawidłowo wychować swojego gryzonia i zapewnić mu odpowiednią aktywność i zabawę. Znajdź cenne wskazówki dotyczące treningu, socjalizacji i odpowiedniego środowiska dla Twojego małego przyjaciela.",
            title:
              "Wychowanie i zabawa gryzoni - trening, socjalizacja i zabawa",
          },
          {
            id: "rodents4",
            name: "ZDROWIE I PIELEGNACJA",
            query: "zdrowie_i_pielegnacja_gryzoni",
            desc: "Zdrowie Twojego gryzonia jest niezwykle ważne. Przeczytaj nasze porady dotyczące właściwej pielęgnacji, profilaktyki zdrowotnej i rozpoznawania najczęstszych schorzeń, aby zapewnić swojemu pupilowi długie i pełne życie.",
            title:
              "Zdrowie i pielęgnacja - zdrowie i dobre samopoczucie pupila",
          },
          {
            id: "rodents5",
            name: "ŻYWIENIE",
            query: "zywienie_gryzoni",
            desc: "Dowiedz się, jak prawidłowo zbilansować dietę swojego gryzonia, aby zapewnić mu wszystkie niezbędne składniki odżywcze. Poznaj odpowiednie pokarmy i unikaj potencjalnie szkodliwych produktów.",
            title: "Żywienie gryzoni - zdrowa i zbilansowana dieta",
          },
        ],
      },
      {
        link: "/blog/ptaki/1",
        name: "PTAKI",
        cat: [
          {
            id: "birds",
            name: "WSZYSTKIE",
            query: "",
            title: "Ptaki - atykuły",
            desc: "Odkryj fascynujący świat ptaków! W tej kategorii znajdziesz informacje na temat różnych gatunków ptaków, ich adopcji, zdrowia i pielęgnacji, żywienia oraz opieki nad dzikimi ptakami. Dowiedz się więcej o tych pięknych stworzeniach i jak możesz zadbać o ich dobrostan.",
          },
          {
            id: "birds1",
            name: "ADOPCJA",
            query: "adopcja_ptakow",
            title: "Adopcja ptaków - czego się spodziewać?",
            desc: "Jeśli rozważasz adopcję ptaka, ta kategoria jest dla Ciebie. Znajdziesz tu informacje na temat adopcji ptaków domowych, jak znaleźć odpowiedniego towarzysza, jak przygotować klatkę i jak zapewnić im odpowiednie warunki życia. Przygarnij pięknego ptaka i daj mu nowy dom pełen miłości.",
          },
          {
            id: "birds2",
            name: "GATUNKI",
            query: "gatunki_ptakow",
            title: "Gatunki ptaków - piękno i różnorodność charakterów",
            desc: "Odkryj różnorodność gatunków ptaków. W tej kategorii znajdziesz informacje na temat różnych gatunków ptaków domowych. Dowiedz się więcej o ich cechach charakterystycznych, zachowaniu, wymaganiach dotyczących środowiska i jak zapewnić im odpowiednie warunki bytowania. Poznaj fascynujący świat ptaków.",
          },
          {
            id: "birds3",
            name: "ZDROWIE I PIELEGNACJA",
            query: "zdrowie_i_pielegnacja_ptakow",
            title: "Zdrowie i pielęgnacja ptaków - wskazówki i porady",
            desc: "Zdrowie i dobre samopoczucie Twojego ptaka są niezwykle ważne. W tej kategorii znajdziesz informacje na temat pielęgnacji ptaków domowych, jak dbać o ich zdrowie, jak rozpoznać i zapobiegać chorobom, oraz jak zapewnić im odpowiednią opiekę i higienę. Zadbaj o zdrowie swojego pupila.",
          },
          {
            id: "birds4",
            name: "ŻYWIENIE",
            query: "zywienie_ptakow",
            title: "Żywienie ptaków - wymagania żywieniowe twojego pupila",
            desc: "Odpowiednie żywienie jest kluczowe dla zdrowia i dobrej kondycji ptaków. W tej kategorii znajdziesz informacje na temat odpowiedniego żywienia ptaków domowych, jakie pokarmy są dla nich najlepsze, jak przygotować zrównoważoną dietę, oraz jakie są ich specyficzne wymagania żywieniowe. Zapewnij swojemu pupilowi smaczne i zdrowe posiłki.",
          },
          {
            id: "birds5",
            name: "WYCHOWANIE",
            query: "wychowanie_ptakow",
            title: "Wychowanie ptaków - porady i wskazówki",
            desc: "Odkryj najlepsze porady dotyczące wychowania ptaków w domu. Dowiedz się, jak zapewnić im odpowiednią opiekę i zdrowe warunki życia. Poznaj tajniki skutecznego treningu i aktywizmu dla Twoich ptaków. Zadbaj o harmonię i szczęście swoich piórkaowych przyjaciół.",
          },
          {
            id: "birds5",
            name: "DZIKIE PTAKI",
            query: "dzikie_ptaki",
            title: "Dzikie ptaki - opieka i pomoc w potrzebie",
            desc: "W tej kategorii znajdziesz informacje na temat opieki nad dzikimi ptakami, jak rozpoznać poszkodowane zwierzęta, jak zapewnić im tymczasowe schronienie i jak skontaktować się z odpowiednimi organizacjami, które zajmują się ich rehabilitacją. Pomóż dzikim ptakom wrócić do zdrowia i wolności.",
          },
        ],
      },
      {
        link: "/blog/akwarystyka/1",
        name: "AKWARYSTYKA",
        cat: [
          {
            id: "aquarium",
            name: "WSZYSTKIE",
            query: "",
            title: "Zwierzęta akwariowe - artykuły",
            desc: "Odkryj fascynujący świat zwierząt akwariowych. W tej kategorii znajdziesz informacje na temat różnych gatunków zwierząt akwariowych, ich żywienia, zdrowia oraz konserwacji zbiornika. Dowiedz się więcej o tych pięknych stworzeniach i jak zapewnić im odpowiednie warunki życia w akwarium.",
          },
          {
            id: "aquarium1",
            name: "GATUNKI",
            query: "gatunki_zwierzat_akwariowych",
            title: "Gatunki zwierząt akwariowych - odkryj niezwykły świat",
            desc: "Odkryj różnorodność gatunków zwierząt akwariowych. W tej kategorii znajdziesz informacje na temat różnych gatunków ryb, krewetek, ślimaków i innych zwierząt, które można trzymać w akwarium. Dowiedz się więcej o ich cechach charakterystycznych, wymaganiach dotyczących środowiska i jak zapewnić im odpowiednie warunki bytowania.",
          },
          {
            id: "aquarium2",
            name: "ŻYWIENIE",
            query: "zywienie_zwierzat_akwariowych",
            title: "Żywienie zwierząt akwariowych - praktyczne wskazówki",
            desc: "Odpowiednie żywienie jest kluczowe dla zdrowia i dobrej kondycji zwierząt akwariowych. W tej kategorii znajdziesz informacje na temat odpowiedniego żywienia. Dowiedz się, jakie pokarmy są dla nich najlepsze, jak przygotować zrównoważoną dietę i jakie są ich specyficzne wymagania żywieniowe.",
          },
          {
            id: "aquarium3",
            name: "ZDROWIE",
            query: "zdrowie_zwierzat_akwariowych",
            title:
              "Zdrowie zwierząt akwariowych - odpowiednia opieka i zapobieganie chorobom",
            desc: "Zdrowie i dobre samopoczucie zwierząt akwariowych są niezwykle ważne. W tej kategorii znajdziesz informacje na temat zdrowia ryb, krewetek, ślimaków i innych zwierząt akwariowych. Dowiedz się, jak dbać o ich zdrowie, jak rozpoznać i zapobiegać chorobom, oraz jak zapewnić im odpowiednią opiekę i higienę.",
          },
          {
            id: "aquarium4",
            name: "KONSERWACJA ZBIORNIKA",
            query: "konserwacja_zbiornika",
            title: "Konserwacja akwarium - jak o nie dbać?",
            desc: "Konserwacja zbiornika akwariowego jest kluczowa dla utrzymania zdrowego i pięknego środowiska dla zwierząt. W tej kategorii znajdziesz informacje na temat konserwacji zbiornika, jak utrzymać odpowiednie parametry wody, jak dbać o rośliny i zwierzęta w akwarium, oraz jak przeprowadzać regularne czyszczenie i konserwację.",
          },
        ],
      },
      {
        link: "/blog/terrarystyka/1",
        name: "TERRARYSTYKA",
        cat: [
          {
            id: "terrarium",
            name: "WSZYSTKIE",
            query: "",
            title: "Terrarystyka - artykuły",
            desc: "W tej kategorii znajdziesz informacje na temat różnych gatunków gadów, płazów i innych stworzeń, które możesz trzymać w terrarium. Dowiedz się o odpowiednich warunkach życia, żywieniu, pielęgnacji i aranżacji terrarium, aby stworzyć odpowiednie środowisko dla swoich podopiecznych.",
          },
          {
            id: "terrarium1",
            name: "GATUNKI GADÓW",
            query: "gatunki_gadow",
            title: "Gatunki gadów w terrarium - cechy i wymagania",
            desc: "Odkryj różnorodność gatunków gadów, które możesz trzymać w terrarium. W tej kategorii znajdziesz informacje na temat charakterystycznych cech, wymagań dotyczących żywienia i warunków życia różnych gatunków gadów. Wybierz odpowiednie zwierzęta do swojego terrarium, biorąc pod uwagę ich potrzeby i preferencje.",
          },
          {
            id: "terrarium2",
            name: "GATUNKI PŁAZÓW",
            query: "gatunki_plazow",
            title: "Gatunki płazów w terrarium - charakterystyka i wymagania",
            desc: "Odkryj różnorodność gatunków płazów, które możesz trzymać w terrarium. W tej kategorii znajdziesz informacje na temat charakterystycznych cech, wymagań dotyczących żywienia i warunków życia różnych gatunków płazów. Wybierz odpowiednie zwierzęta do swojego terrarium, biorąc pod uwagę ich potrzeby i preferencje.",
          },
          {
            id: "terrarium3",
            name: "ZDROWIE I PIELEGNACJA",
            query: "zdrowie_i_pielegnacja_terrarium",
            title: "Zdrowie i pielęgnacja - jak zapewnić odpowiednią opiekę",
            desc: "Dowiedz się, jak prawidłowo dbać o zdrowie i pielęgnację gadów i płazów trzymanych w terrarium. W tej kategorii znajdziesz porady dotyczące żywienia, utrzymania odpowiednich warunków środowiskowych, dbania o higienę i rozwiązywania problemów zdrowotnych. Zapewnij swoim podopiecznym odpowiednią opiekę, aby cieszyć się ich pięknem i zdrowiem.",
          },
          {
            id: "terrarium4",
            name: "ŻYWIENIE",
            query: "zywienie_terrarium",
            title: "Żywienie zwierząt terrarystycznych - jaki pokarm wybrać?",
            desc: "Dowiedz się, jak prawidłowo żywić swoje gady i płazy trzymane w terrarium. W tej kategorii znajdziesz informacje na temat odpowiednich diet, żywych i martwych pokarmów, suplementacji i innych aspektów związanych z żywieniem. Zapewnij swoim podopiecznym odpowiednie odżywienie, aby utrzymać ich zdrowie i dobre samopoczucie.",
          },
          {
            id: "terrarium5",
            name: "URZĄDZANIE TERRARIUM",
            query: "urzadzanie_terrarium",
            title: "Urzadzanie terrarium - praktyczne wskazówki i porady",
            desc: "Stwórz atrakcyjne i funkcjonalne terrarium dla swoich gadów i płazów! W tej kategorii znajdziesz porady dotyczące aranżacji, wyboru podłoża, roślin, dekoracji i innych elementów, które pomogą stworzyć odpowiednie środowisko dla Twoich podopiecznych. Zapewnij im miejsce, w którym będą czuć się komfortowo i bezpiecznie.",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    link: ".",
    name: "SKLEP",
  },
  {
    id: 4,
    link: ".",
    name: "KONTAKT",
  },
];
